### ISSUE TITLE
finger_action_group error

### ISSUE THREAD

**Issue by fossfreedom** [asermax/lastfm_extension#10]
~/.local/share/rhythmbox/plugins/lastfm_extension$ rhythmbox
Traceback (most recent call last):
  File "/home/dad/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 148, in do_activate
    self.conection_changed( self.settings, Keys.CONNECTED, manager )  
  File "/home/dad/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 401, in conection_changed
    self.activate_fingerprinter( self.settings, Keys.FINGERPRINTER, manager )
  File "/home/dad/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 369, in activate_fingerprinter
    manager.remove_action_group( self.finger_action_group )
AttributeError: 'LastFMExtensionPlugin' object has no attribute 'finger_action_group'

ok - this was found with a clean ubuntu install - I had just installed my "debian package" version of pylastfp, git cloned the lastfm_extension repository and run ./install.sh

Then started rhythmbox - no plugins enabled.  Activated lastfm-extension.  Did not go into preferences so fingerprint is not yet enabled.  Restarted rhythmbox and this is when I noted the error in the terminal.

**Comment by asermax** [comment]
There was an error in my logic for the if's, forgot to take into account the initial case where the fingerprinter wasn't enabled.
Let me know if it works, and thanks for the report!
