### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by lumnn** [asermax/lastfm_extension#19]
When I start rhythmbox from terminal:

```
Traceback (most recent call last):
  File "/home/kamil/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 434, in do_activate
    LastFMExtensionBag.initialise_instance(self, settings)
  File "/home/kamil/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 384, in initialise_instance
    cls.instance = LastFMExtensionBag(plugin, settings)
  File "/home/kamil/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 338, in __init__
    extension = extension_class(plugin, settings)
  File "/home/kamil/.local/share/rhythmbox/plugins/lastfm_extension/extensions/LastFMExtensionPlaycountSync.py", line 41, in __init__
    self._full_sync_man = FullPlaycountSyncManager(self.network, self.db,
AttributeError: 'Extension' object has no attribute 'network'
```

**Comment by asermax** [comment]
Noted, I'll give it a look when I have a chance and I'll let you know!

**Comment by asermax** [comment]
I believe the last commit should fix this issue.
@suhy if you can, please give a look and let me know!

**Comment by lumnn** [comment]
Stil problem exists:

```  File "/home/kamil/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 434, in do_activate
    LastFMExtensionBag.initialise_instance(self, settings)
  File "/home/kamil/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 384, in initialise_instance
    cls.instance = LastFMExtensionBag(plugin, settings)
  File "/home/kamil/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 338, in **init**
    extension = extension_class(plugin, settings)
  File "/home/kamil/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 254, in **init**
    super(LastFMExtensionWithPlayer, self).**init**(plugin, config)
  File "/home/kamil/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 66, in **init**
    self.on_enabled_notify(self.enabled, plugin)
  File "/home/kamil/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 107, in enabled
    return self.settings.getboolean(Keys.ENABLED)
  File "/home/kamil/.local/share/rhythmbox/plugins/lastfm_extension/LastFMExtensionUtils.py", line 166, in call_with_section
    return getattr(self._settings, attr)(self._section, _args, *_kwargs)
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'enabled' in section: 'LastFMLoveBan'

```

My Rhythmbox vesion is 2.97
```

**Comment by asermax** [comment]
Well, we're advancing, that's a different problem at least d: I'll keep on it!

**Comment by asermax** [comment]
Alright, made somo more changes and tried testing out myself (this problems happen when you don't have yet a configuration files, so I deleted mine to test). It seems to be working fine, let me know how it seems for you!

**Comment by lumnn** [comment]
Thanks! It works! :)

**Comment by asermax** [comment]
Nice! Thanks for reporting the bug :]
Feel free to open another issue over here for any problem you may have or any enhancement you want to see implemented.
